
import os


# for stream 
MULTI_CLIENT:bool = False
multi_clients, work_loads = {}, {}


# necessary
PREFIX = True
TOKEN: str = os.getenv('TOKEN', '6913439784:AAFwzP6uBQrjW9fkFb1FaADqnQbDm0')
DB_URL: str = os.getenv('DB_URL', 'mongodb+srv://nandhaxd:hIahsjjPX3@cluster0.80igexg.mongodb.net')
DB_URL2: str = os.getenv('DB_URL2', 'mongodb+srv://nandhasigma:vnfVompdkskskkssE3AK@cluster0.gt47zau.mongodb.net')
BOT_ID: int = int(TOKEN.split(':')[0])
API_ID: int = 18257951

API_HASH: str = "d8ea642aedb7bc05f0cfd477"
SUPPORT_CHAT = '@GojoAssistantChat'
UPDATE_CHANNEL = '@NandhaBots'
LOGS_CHANNEL =  5696053228 #'@GojoAssistant'
BOT_USERNAME = '@GojoAssistantBot'
BOT_NAME = "Gojo Saturo"
IS_WEB_SUP = True

DEV_LIST = [
  5696053228, # t.me/nandha
]

SPAM_USERS = {}

PREMIUM_USERS = []
PREMIUM_USERS.extend(DEV_LIST)



#vc player
USER_STRING = "BQHCct8AOtz22BEAvc5FGHs7h-wblZmtZRHTVIiZHjFUJXoAde1QlomW8k848q2OAILKkN5moElb3J5Osj7sAZlB0HmnmPqOJFd-JbCBEET5Z-dcB3BZ8prm8uxFHpDbAjWtc2j3lRH4GTc2tkS_Yck8CGJtxwTpk4BCTiiHeadY0FArIG0utRDL8I7qturSU45FDaMBRvvFJ876-WQ66PKvyeQWxWJhbNPi9JzSE-a8F-PqSiXCmPI8R5gKfUuHLlvLIpIyJOKIZmpoU3FuV847XqM4IWHdA1ONnOE_A6jsPIKD7H8u_xTZqtsIsu4qEwzhIiy742Z9q5fVhoYcOosfG29s7AAAAAF-Xh-4AA"

#gist
GIST_TOKEN = "github_pat_11AVKME9WCXomC73WuVYtOnQdOxG08cfzcfDQ5NZEF2M3HHJYFmNI"


# keep alive ( web support )
WEB_URL = "https://makima-lover.onrender.com/"
KEEP_ALIVE = True
PORT = int(os.environ.get("PORT", 8080))
BIND_ADDRESS = str(os.environ.get("WEB_SERVER_BIND_ADDRESS", "0.0.0.0"))
WEB_SLEEP = 4*60

# pagination & stuffs
AUTO_DEL = 10
BTN_COLUMNS = 4
BTN_ROWS = 7


# some media source
PM_START_IMG = "AgACAgQAAxkDAAECcMhndPIEtfNJJFeNC6HtpnPrBdMBsgACO7QxG2M4RFCks6CwauexWAEAAwIAA3kAAzYE"
HELP_CMD_IMG = "AgACAgQAAxkDAAECcQpndPLyZj0IsU6ZdSnsZj-phMLGIAACvLQxG_DZRFDyiIVZuXpsHQEAAwIAA3kAAzYE"
HELP_MODULE_IMG = "AgACAgQAAxkDAAECcRZndPaa-qXg8b3KyCaxo28sFgAB17wAAuu0MRuFFIRRk8_kSHQ2jqUBAAMCAAN5AAM2BA"
START_IMG = "AgACAgUAAx0CdvJ-DQACQENnFJeDdSaiI6usIlegL_25krbWqQACBcExG1tvqFRGAAHGxB5g88ABAAMCAAN4AAM2BA"
FORCE_JOIN_IMG = "AgACAgUAAxkBAAECo71nejtOVOcAAbVnqDfRWtREw8Rj2vkAAljBMRsfkdlXHka_9cfD7EEBAAMCAAN5AAM2BA"

AF_START_STICKERS = [
  "CAACAgUAAxkBAAEBrV9nWukpft8gmtrZVMkbO4GKlZy0HQACWxUAAnHv2FZkjr7WjG3OjzYE",
  "CAACAgUAAxkBAAEBrVpnWuhM17A8xDlzxO2q5aqSa6xmawACMRMAAlpM2VYGl0Ro6224bjYE",
  "CAACAgUAAxkBAAEBrWJnWulBrVl7pq-QRI1QCaMjd6laLAAC2RYAAojK2Va2m-0pJ2vqLzYE"
]

STICKERS = {
"CAACAgQAAxkBAAECdO1ndW8ICjKDXuzrYsEo5hqQbVw6rAAC7w4AAjULSFDuxCh0capMYDYE",
"CAACAgQAAxkBAAECdPBndW8Sdvfw4Ppj87fy_npiIdJfDwACPBEAAg1eUVAboAI8ZLYkXTYE",
"CAACAgQAAxkBAAECdPNndW8utxbCZtWzQmf5ZsttjCmgjwACfhIAApO7UVDWdRWcykiwuDYE",
"CAACAgQAAxkBAAECdPZndW9Suh_gnSo8lD3WAsbCiISpYAACyA4AAiOqKVKUg3R3m5-gqjYE",
"CAACAgQAAxkBAAECdPlndW9cYXPSw39cyQHvE6nEdNB2JQACCBIAAtn8IFK1g1MaQBON0TYE",
"CAACAgQAAxkBAAECdPxndW9kD86_lqdWJszPI8vYbcyvngAC_REAAo_vSVJCrH8aUlOkyTYE",
"CAACAgQAAxkBAAECdP9ndW-Ia3qf4pXbjWZI8Y0-bz2DogACqBEAAtDXMFItdGU77Edd_TYE",
"CAACAgQAAxkBAAECdQJndW-dkLNejsHkTINe_Qxq3I08EwACITUAApRgTgOL1gVo29ff0TYE",
"CAACAgQAAxkBAAECdQVndW-wKUWRXxpUA4J_kh-PIG_9UwACKzcAApRgTgPiRf7a32h5vTYE",
"CAACAgIAAxkBAAECdQhndW_A211FzHXaW7Aw4RaMJF6tIgACsTEAAi_24UiQKhNSL9u30DYE",
"CAACAgIAAxkBAAECdQtndW_Ij8fMRzlbT3X_TfzVK1T8rAAC0C8AAodj4EjSZ1G3qw6FCDYE",
"CAACAgIAAxkBAAECdQ5ndW_VDdwsZNXZZax-TKaBfewtdQACiUsAArp5-EnWQpanpxF8yTYE",
"CAACAgIAAxkBAAECdRFndW_dd4wVOgwgFEkbi8dAM9XSlgACOEUAAnVA-En_oC_69i7LEzYE",
"CAACAgIAAxkBAAECdRRndW_v2TMrVzit9rYXYqczPlbkCQACsjsAAntc-EmVS7vTfBuJjzYE",
"CAACAgIAAxkBAAECdRdndXAIM_S1ZGNKci1kTAMPyvYNqgACwUoAAv4V8EkLHWsQUvK1gDYE",
"CAACAgIAAxkBAAECdRpndXAVErJDP8CnfHzdO-NswYwhFAACO1YAAkvCKUnA3XYg4FCWlTYE",
"CAACAgIAAxkBAAECdR1ndXAfoKxdgT2fkedoA4fS3m22lgACU1cAAthfKUkuBdehSY_rBzYE",
"CAACAgIAAxkBAAECdSBndXAmzGwiIEAljqKzCQlAY8TLMgACx2MAAuliKUlThRsve-oJyzYE",
"CAACAgUAAxkBAAECdSNndXBJquluZXwU0__JKxmfKMZDEAAChQ8AAqGacVXhgiCsahAGDzYE",
"CAACAgIAAxkBAAECdSZndXBapGEYja7rsroogCRodsny8AACozYAAiQP2EpVNGifwVsKjDYE",
"CAACAgIAAxkBAAECdSlndXBhosJB417LBilVJjF3BZo67AAC9EEAAsku0UqCpzP2ZVFhDTYE",
"CAACAgIAAxkBAAECdSxndXBurDS6bwIK8Qa1oR7veFCbiwACgDwAAjEl0Eomm59IgqSggTYE",
"CAACAgIAAxkBAAECdTJndXB5W3ezZamw35dpDjku80jgGgACGV8AAsU1OUqb69FyFb1c6jYE",
"CAACAgIAAxkBAAECdTVndXCbx0W9t_H2nUrd-Fl3KbUyyQACtj0AAg-5MUgE2eOcan38NjYE",
"CAACAgIAAxkBAAECdThndXClCzM7QcM77Nyuqcl_4dGp1AACPUYAAj1uMUjiLGn4YGxk9jYE",
"CAACAgIAAxkBAAECdT5ndXDVpuuQ8KvuMElfRT8kGOUp4gACHUYAAtMKMEgcf_DY6DSaXDYE",
"CAACAgIAAxkBAAECdURndXDsel2azVwIeyexmf-aMwNBLAAC-h8AAsDtmUlWim3BbUtNfDYE",
"CAACAgIAAxkBAAECdUdndXD4ih8jckxT-Hl3ZwxwxUzX0QACXCAAAhK-mEl6EeOdleoZZjYE",
"CAACAgIAAxkBAAECdUpndXEBmz2IpWxVWkbXz7mgvQlB1AAC-x8AAisNmEla-bbrY-25jTYE",
"CAACAgIAAxkBAAECdU1ndXEfJf6FXFOFL-w32FeXISTBvwAC4GcAAisfOEvOuPgyh_L6izYE",
"CAACAgIAAxkBAAECdVBndXE86_uoi8WCXgJ-1mjFaysxEgACWjYAAu1_-UlGpKXB9t-AwDYE",
"CAACAgIAAxkBAAECdVdndXGp48JGRAOe7zPQoJi5D3VxXQACQTgAApJ5-Emh0g5pFxiGnzYE",
"CAACAgIAAxkBAAECdVpndXGyPJthODJ8NuK6rtD3Vwua6QAC7jQAAkqo-EkdGBrhbITUEDYE",
"CAACAgIAAxkBAAECdV1ndXG_l-bUo46JvIM4Hxj8YEQaOQACtC0AAvs2-UmnONqktEwhTzYE",
"CAACAgIAAxkBAAECdWBndXHG29vG_dZMhvJlK4c07Ss3TQACeS8AAlPL-EkItgVnal3GBjYE",
"CAACAgIAAxkBAAECdV1ndXG_l-bUo46JvIM4Hxj8YEQaOQACtC0AAvs2-UmnONqktEwhTzYE",
"CAACAgIAAxkBAAECdWZndXIBjJ9rDtKutvip87-tAkSQ0QACgi4AAiXucUmJnZzoSNSCvDYE",
"CAACAgIAAxkBAAECdWlndXIQoHORueLutW0sMp7kYgABE1MAAoxHAAIltelK4So4wQ12bcc2BA",
"CAACAgIAAxkBAAECdWxndXIZcekEGymNrjhI5gWIZlOx7QACPkgAAlhi4UrkSTRqKK8iwDYE",
"CAACAgIAAxkBAAECdW9ndXIlwbYgNzDsW41v27Z7yMFf0QACzVEAAj1u4EpQbl_Qdr1NJDYE",
"CAACAgIAAxkBAAECdXJndXJDBU6b5wFDwuGkTAjUynRwiAACkzMAAkvCmUgudR-apFOqGDYE",
"CAACAgIAAxkBAAECdXVndXJIUh28BNFPmzgPXzAN7vtL1AACekYAAkCnmUgiILqmlERFLzYE",
"CAACAgIAAxkBAAECdXhndXJQk7bAMVF9S7x_KV48iYe0cQACzzUAAoavsUhVPK3wUyiO-TYE",
"CAACAgQAAxkBAAECdXtndXJwFKOSFC9ik9hMc9lfRqdqsQACYxYAAvMUAAFSZQEXkaJdECc2BA",
"CAACAgQAAxkBAAECdX5ndXJ6gSGAGc9EThFUPm91mXV5WwACxRUAAlCTCVKxsL-4uYPFCzYE",
"CAACAgQAAxkBAAECdYFndXKA1aRfjr-Yb8IQK8NHaT_FRAAC_BUAAukESFI1AYxe3mz5YTYE",
"CAACAgQAAxkBAAECdYRndXKS3hmAoqlJyk7DkkDl-6-VOAAC-RUAAjrfCFLxhnNCQsfBPzYE",
"CAACAgQAAxkBAAECdYdndXKYUdgAAdfgZDJWHXVF4MUD6rYAAp8UAALqEQhSLZd3lUNZuvU2BA",
}


AF_PHOTOS = [
'AgACAgUAAxkBAAECo-tnej70ZWYrv0bQPM_XRre1lLK6cwACXsExGx-R2VenYteJPUaIjAEAAwIAA3kAAzYE',
'AgACAgUAAxkBAAECo-1nej706PWzzWvmOLAFagdYeONKvgACYMExGx-R2VfM2MDvp7f_9AEAAwIAA3kAAzYE',
'AgACAgUAAxkBAAECo-xnej70d68zKUx_NBuEz3PMZFa13AACX8ExGx-R2Vdc_HYt-dTN6gEAAwIAA3kAAzYE',
'AgACAgUAAxkBAAECo-5nej70IKBWUFDTjky0eAj6Q6KoMAACYcExGx-R2VcD_ZuS0CkwSAEAAwIAA3kAAzYE',
'AgACAgUAAxkBAAECpCVnekCldWbkBNdrjo6EsmTXJ9SLeQACZsExGx-R2Ve6FxfQ5ov_sAEAAwIAA3kAAzYE'
]






#autofilter & file store
AF_USERS = []
AF_USERS.extend(DEV_LIST) # load devs
AF_CHANNEL_LINK = "https://t.me/+Y6D5EM42SwI3MTU1"
AF_CHANNEL_ID = -1002537451901

STREAM_MOD = False
AF_FILE_DEL_TIME = 30*60
AF_SUB_CHAT = "@NandhaBots"
FILE_DB_CHANNEL = -1002178137218 # file store channel
AF_SUB_TEXT = """
<blockquote><b>
To access your files, first click on [📢 Join Our Channel/Group]. Once you've joined, click the [📁 Get File] button to download your files. We're glad to have you with us!

Thank you for being part of our community! 📲 ✨
</b></blockquote>
"""
AF_QS_TEXT = """
🔎 <b>Quick Search</b>:
<blockquote>Select the below buttons to get accurate results for language, media type, etc.</blockquote>
"""


MODULE = {} # all loaded help commands


